### ISSUE TITLE
Indent keyframe animation & media query contents

### ISSUE THREAD

**Issue by JakeSidSmith** [JakeSidSmith/react-style-sheets#2]
```css
@keyframes name {
/* The below needs indenting */
0% {
  opacity: 1;
}

100% {
  opacity: 0;
}

}
```
